### ISSUE TITLE
В документации не указан ключ " .certificates.spec.usage" и его назначение

### ISSUE THREAD

**Issue by nnlkcncff** [fraima/key-keeper#10]
Кажется, ключ " .certificates.spec.usage" ни на что не влияет и носит только описательную функцию о назначении сертификата. Однако, это явно не указано. Пожалуйста, отразите это в документации.

**Comment by FR-Solution** [comment]
Это не так usages описывают какой тип у сертификата 

https://github.com/fraima/terraform-modules/blob/f248e5e876f8ef95708864082e2331c6e33ce634/modules/k8s-config-vars/locals.certs.tf#L103

Тут пример использования
